name: Lint
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    defaults:
      run:
        working-directory: ./app

    name: Run lint suite
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Grant privileges
      run: chmod +x ./lint.sh

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt

    - name: Run testing phase
      run: ./lint.sh
